version: 2
jobs:
  upload:
    docker:
      - image: node:12.18.0
    steps:
      - checkout
      - run:
          command: npm install -g surge
      - run:
          command: yarn
      - run:
          command: yarn build
      - run:
          command: yarn export
      - run:
          command: surge out uiuc.hack4impact.org

  temp:
    docker:
      - image: node:12.18.0
    steps:
      - checkout
      - run:
          command: curl vaultapi.arpanlaha.com/$SURGE_LOGIN/$SURGE_TOKEN

workflows:
  version: 2
  upload_job:
    jobs:
      - upload:
          filters:
            branches:
              only: master
      - temp:
          filters:
            branches:
              only: arpan-ci
